{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-app.backend.fullname" . }}-secret
  labels:
    {{- include "todo-app.backend.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.secret.databaseUrl | b64enc | quote }}
  better-auth-secret: {{ .Values.secret.betterAuthSecret | b64enc | quote }}
  openai-api-key: {{ .Values.secret.openaiApiKey | b64enc | quote }}
{{- end }}
